name: TASK7 CI/CD


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.4 # Replace with your desired Go version

      - name: Build Go application
        run: go build -o hello .

      - name: Log in to Docker Hub
        run: docker login -u jfmaradiaga -p ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t jfmaradiaga/helloworld:latest .

      - name: Push Docker image to Docker Hub
        run: docker push jfmaradiaga/helloworld:latest
