name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t jfmaradiaga/helloworld:latest .

      - name: Log in to Docker Hub
        run: docker login -u jfmaradiaga -p Blacksteeljm120288$

      - name: Push Docker image
        run: docker push jfmaradiaga/helloworld:latest
        
