- name: "Ubuntu - Install Docker"
  hosts: all
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Stop Docker containers
      become: yes
      command:
        cmd: docker stop $(docker ps -a -q)
      ignore_errors: true

    - name: Remove Docker containers
      become: yes
      command:
        cmd: docker rm $(docker ps -a -q)
      ignore_errors: true

    - name: Update all packages
      apt:
        upgrade: dist
      become: yes

    - name: Ensure a list of packages are installed
      apt:
        name:
          - python3-pip
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
        state: latest
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Enable Docker service at startup
      service:
        name: docker
        state: started
        enabled: yes

    - name: Upgrade pip
      become: yes
      command:
        cmd: python3 -m pip install pip --upgrade

    - name: Ensure Python pip packages are installed
      pip:
        name:
          - boto
          - boto3
          - docker-compose
        executable: /usr/bin/pip3

    - name: Add user to the docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

    - name: Pull Docker Image
      become: yes
      command:
        cmd: docker pull jfmaradiaga/helloworld:latest

    - name: Run Docker container
      become: yes
      command:
        cmd: docker run -d -p 8080:8080 jfmaradiaga/helloworld:latest

