- name: "Ubuntu - Install Docker"
  hosts: 3.95.225.27
  remote_user: ubuntu
  become: yes
  tasks:
    - name: Update all packages
      apt:
        upgrade: dist

    - name: Ensure a list of packages are installed
      apt:
        name: "{{ packages }}"
        state: latest
        update_cache: yes
      vars:
        packages:
          - python3-pip
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes
        cache_valid_time: 86400

    - name: Install Docker packages
      apt:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
          - docker-ce
          - docker-ce-cli
          - containerd.io

    - name: Enable Docker service at startup
      service:
        name: docker
        state: started
        enabled: yes

    - name: Upgrade pip
      shell: "python3 -m pip install pip --upgrade"

    - name: Ensure Python pip packages are installed
      pip:
        name: "{{ packages }}"
        executable: /usr/bin/pip3
      vars:
        packages:
          - boto
          - boto3
          - docker-compose

    - name: Add user to the docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

- name: Pull and deploy Docker image
  hosts: all
  tasks:
    - name: Pull Docker image
      docker_image:
        name: jfmaradiaga/helloworld:latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: helloworld
        image: jfmaradiaga/helloworld:latest
        state: started
        ports:
          - "8080:80"
