- name: Install Docker
  hosts: 3.86.92.128
  remote_user: ubuntu  # Replace with the appropriate SSH user for your EC2 instance
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_private_key_file: ${{ secrets.SSH_PRIVATE_KEY }}

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present

  tasks:
    - name: Install Docker dependencies
      apt:
        name: 
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
      become: true

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      become: true

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable
        state: present
      become: true

    - name: Install Docker engine
      apt:
        name: docker-ce
        state: present
      become: true

    - name: Add user to the docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: true

- name: Pull and deploy Docker image
  hosts: all
  tasks:
    - name: Pull Docker image
      docker_image:
        name: jfmaradiaga/helloworld:latest
        source: pull

    - name: Run Docker container
      docker_container:
        name: helloworld
        image: jfmaradiaga/helloworld:latest
        state: started
        ports:
          - "8080:80"
