# Use an official Go runtime as the base image
FROM golang:1.16

# Set the working directory
WORKDIR /app

# Copy the Go application files
COPY . .

# Build the Go application
RUN CGO_ENABLED=0 GOOS=linux go build -o cli hello.go

# Expose the necessary port
EXPOSE 8080

# Start the application
CMD ["./cli", "0.0.0.0:8080"]







# Set the command to run when the container starts
#CMD ["./cli 192.168.122.129:8080"]
