stages:
  - build
  - deploy

build:
  image: docker:latest
  stage: build
  services:
    - docker:dind
  script:
    - docker build -t jfmaradiaga/helloworld:latest .

deploy:
  image: docker:latest
  stage: deploy
  services:
    - docker:dind
  script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker push jfmaradiaga/helloworld:latest
