name: Deploy to EC2 with Ansible

on:
  push:
    branches:
      - main

env:
  ANSIBLE_HOST_KEY_CHECKING: false

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install Ansible and docker
        run: |
          sudo apt-get update
          sudo apt-get install -y ansible
          sudo apt install docker.io -y
          sudo apt install podman-docker -y
      
      - name: Start Docker service
        run: sudo service docker start

      - name: Run Ansible playbook
        run: |
          ansible-playbook playbook.yml \
            -e "docker_image=jfmaradiaga/helloworld:latest" \
            -e "ec2_public_ip=${{ secrets.EC2_PUBLIC_IP }}"

