name: Android Deployment

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: flutter build apk
      - uses: actions/upload-artifact@v3
        with:
          name: android-debug.apk
          path: build/app/outputs/flutter-apk/app-debug.apk

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: android-debug.apk
          path: .
      - run: firebase deploy --task17-df08a
