name: Flutter Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          distribution: "zulu"
          java-version: "11"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"

      - name: Set working directory to the Flutter project
        run: cd task17/task17

      - name: Show current directory
        run: pwd

      - name: Get Flutter Dependencies
        run: |
          cd /home/runner/work/DevOpsGYMBatch3/DevOpsGYMBatch3/task17/task17
          flutter clean
          flutter config --no-analytics  # Disable telemetry
          flutter pub get --disable-telemetry
          flutter build apk

      - name: Upload APK artifact to Firebase
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.APPID }}
          token: ${{ secrets.FIREBASE_TOKEN }}
          groups: pre-tester
          file: build/app/outputs/apk/release/app-release.apk
